### ISSUE TITLE
Fatal Error in Footer

### ISSUE THREAD

**Issue by ronalfy** [BinaryMoon/jarvis#3]
Fatal error: Uncaught Error: 

```bash
Call to undefined function jarvis_social_links()
in /Applications/MAMP/htdocs/wordpress/wp-content/themes/jarvis/footer.php:27 Stack trace: #0 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(722): require_once() #1 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(671): load_template('/Applications/M...', true) #2 /Applications/MAMP/htdocs/wordpress/wp-includes/general-template.php(76): locate_template(Array, true) #3 /Applications/MAMP/htdocs/wordpress/wp-content/themes/jarvis/singular.php(49): get_footer() #4 /Applications/MAMP/htdocs/wordpress/wp-includes/template-loader.php(78): include('/Applications/M...') #5 /Applications/MAMP/htdocs/wordpress/wp-blog-header.php(19): require_once('/Applications/M...') #6 /Applications/MAMP/htdocs/wordpress/index.php(17): require('/Applications/M...') #7 {main} thrown in /Applications/MAMP/htdocs/wordpress/wp-content/themes/jarvis/footer.php on line 27
```

**Comment by BinaryMoon** [comment]
Thanks - I fixed this.

I am pretty sure I used this same code in a number of themes, so I'll need to make sure those older themes don't have the same problem.

And do more testing without Jetpack enabled!
